### ISSUE TITLE
Parsing fails with an IPv6 address

### ISSUE THREAD

**Issue by quejacq** [lpinca/forwarded-parse#7]
Parsing fails when given an IPv6 address

```
console.log(
  parse('by=3.235.38.58;for=2001:861:3a42:b7b0:9971:120a:391f:f585,for=64.252.138.139;host=api.whatever.tld;proto=https')
);

/***
/.../node_modules/forwarded-parse/index.js:121
          throw new ParseError(unexpectedCharacterMessage(header, i), header);
          ^
ParseError: Unexpected character ':' at index 23
    at parse (/.../node_modules/forwarded-parse/index.js:121:17)
    at Object.<anonymous> (/.../test.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  input: 'by=3.235.38.58;for=2001:861:3a42:b7b0:9971:120a:391f:f585,for=64.252.138.139;host=api.whatever.tld;proto=https'
}
*/
```

**Comment by lpinca** [comment]
See https://datatracker.ietf.org/doc/html/rfc7239#section-4 and https://datatracker.ietf.org/doc/html/rfc7239#section-6.

The `2001:861:3a42:b7b0:9971:120a:391f:f585` value in your example is not valid. It should be
`"[2001:861:3a42:b7b0:9971:120a:391f:f585]"`.

**Comment by quejacq** [comment]
Thank you for your reply. The value is as-is from Amazon's web proxies, I will see how to make it RFC compliant.
